import prlsdkapi
import prlsdkapi.prlsdk.consts as consts

prlsdkapi.init_server_sdk()

local = prlsdkapi.Server()
local.login("127.0.0.1", "root", "1q2w3eQAZ").wait()

#flags = consts.PVTF_VM | consts.PGVLF_FILL_AUTOGENERATED
flags = consts.PVTF_VM | consts.PGVLF_GET_ONLY_IDENTITY_INFO | consts.PGVLF_FILL_AUTOGENERATED
for i in local.get_vm_list_ex(flags).wait():
  print("VM: %s, isTemplate: %d" % (i.get_name(), i.is_template()))

